name: Generate Weekly Climate Report

on:
  schedule:
    - cron: '0 6 * * 1'  # every Monday 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        env:
          USE_REAL_DATA: '0'
        run: |
          python scripts/generate_report.py

      - name: Commit report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/research_report.pdf reports/*.png data/climate_dataset.csv
          git commit -m "chore: auto-generate report $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit."
          git push origin HEAD:main
