name: Generate Weekly Climate Report

on:
  schedule:
    - cron: '0 6 * * 1'  # every Monday 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate CSV report (real data)
        env:
          USE_REAL_DATA: '1'
        run: |
          python scripts/generate_report.py

      - name: Commit CSV only
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: update CSV climate data $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No CSV changes."

