name: Update timeseries data

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate timeseries
        run: |
          python scripts/update_timeseries.py

      - name: Commit CSV updates
        run: |
          set -eo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f data/global_timeseries.csv data/continent_timeseries.csv data/latest_snapshot.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update timeseries $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
